//   --// waybar config generated by wbarconfgen.sh //--   //

{
// sourced from header module //

    "layer": "top",
    "position": "top",
    "mod": "dock",
    "height": 33,
    "exclusive": true,
    "passthrough": false,
    "gtk-layer-shell": true,
    "reload_style_on_change": true,


// positions generated based on config.ctl //

	"modules-left": ["custom/padd","custom/l_end","custom/menu", "custom/notification", "network", "bluetooth","group/info", "custom/r_end", "custom/l_end","mpris","custom/r_end"],

	"modules-center": ["custom/padd","custom/l_end","idle_inhibitor","hyprland/workspaces#kanji","custom/r_end","custom/padd"],

	"modules-right": ["custom/l_end","backlight","pulseaudio","custom/r_end","custom/l_end","battery","custom/r_end",
  "custom/l_end","clock", "custom/power","custom/r_end", "custom/padd"]
  ,



// sourced from modules based on config.ctl //
"custom/menu": {
	"format": "󰘳{}",
	"exec": "echo ; echo 󱓟 app launcher",
	"interval": 86400, // once every day
	"tooltip": true,
	"on-click": "pkill rofi || rofi -show drun -modi run,drun,filebrowser,window",
	"on-click-middle": "~/.config/hypr/UserScripts/WallpaperSelect.sh",
	"on-click-right": "~/.config/hypr/scripts/WaybarLayout.sh",
},

 "custom/notification": {
            "tooltip": false,
            "format": "",
            "on-click": "swaync-client -t -sw",
            "escape": true
        },

 "group/info": {
    "orientation": "inherit",
    "drawer": {
      "transition-duration": 300,
      "transition-left-to-right": false,
    },
    "modules": ["custom/arrow_right", "cpu", "memory", "temperature"],
  },
  "custom/arrow_right": {
    "format": "󰁙",
    "tooltip": false,
  },
  "cpu": {
    "format": "| 󰘚 {usage}󱉸",
  },
  "memory": {
	"interval": 10,
	"format": " 󰾆 {used:0.1f}G ",
	"format-alt": "󰾆 {percentage}%",
	"format-alt-click": "click",
	"tooltip": true,
	"tooltip-format": "{used:0.1f}GB/{total:0.1f}G",
	"on-click-right": "kitty --title btop sh -c 'btop'"
},

"temperature": {
	"interval": 10,
	"tooltip": true,
	"hwmon-path": [
		"/sys/class/hwmon/hwmon6/temp1_input",
		"/sys/class/thermal/thermal_zone0/temp"
	],
	//"thermal-zone": 0,
	"critical-threshold": 82,
	"format-critical": "{icon} {temperatureC}°C",
	"format": "{icon} {temperatureC}°C",
	"format-icons": [
		"󰈸"
	],
	"on-click-right": "kitty --title nvtop sh -c 'nvtop'"
},


"mpris": {
	"interval": 1,
	"format": "{player_icon} <i>{dynamic}</i>",
	"format-paused": "{status_icon} <i>{artist} {title}</i>",
	"on-click-middle": "playerctl play-pause",
	"on-click": "playerctl previous",
	"on-click-right": "playerctl next",
	"scroll-step": 5.0,
	"on-scroll-up": "$HOME/.config/hypr/scripts/volume.sh --inc",
	"on-scroll-down": "$HOME/.config/hypr/scripts/volume.sh --dec",
	"smooth-scrolling-threshold": 1,
	"tooltip": true,
	"tooltip-format": "{status_icon} {dynamic}\nLeft Click: previous\nMid Click: Pause\nRight Click: Next",
	"player-icons": {
		"chromium": "",
		"default": "",
		"firefox": "",
		"kdeconnect": "",
		"mopidy": "",
		"mpv": "󰐹",
		"spotify": "",
		"vlc": "󰕼",
	},
	"status-icons": {
		"paused": "󰐎",
		"playing": "",
		"stopped": "",
	},
	"dynamic-order": ["artist", "title"],
	"ignored-players": ["firefox", "zen"],
	"max-length": 43,
	
	    "on-click": "playerctl play-pause",
	    "on-click-right": "playerctl next",
	    "on-click-middle": "playerctl previous",
	    "tooltip": true,
	    "tooltip-format": "{player} ({status})\n{artist} - {title}"
},


        "bluetooth": {
            "format-on": "󰂯",
            "format-off": "BT-off",
            "format-disabled": "󰂲",
            "format-connected-battery": "{device_battery_percentage}% 󰂯",
            "format-alt": "{device_alias} 󰂯",
            "tooltip-format": "{controller_alias}\t{controller_address}\n\n{num_connections} connected",
            "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{num_connections} connected\n\n{device_enumerate}",
            "tooltip-format-enumerate-connected": "{device_alias}\n{device_address}",
            "tooltip-format-enumerate-connected-battery": "{device_alias}\n{device_address}\n{device_battery_percentage}%",
            "on-click-right": "blueman-manager",
        }, 


    "custom/power": {
        "format": "{}",
        "rotate": 0,
        "exec": "echo ; echo  logout",
        "on-click": "logoutlaunch.sh 2",
        "on-click-right": "logoutlaunch.sh 1",
        "interval" : 86400, // once every day
        "tooltip": true
    },

  
	"wlr/taskbar": {
		"format": "{icon}",
		"rotate": 0,
		"icon-size": 18,
		"icon-theme": "Tela-circle-dracula",
        "spacing": 0,
		"tooltip-format": "{title}",
		"on-click": "activate",
		"on-click-middle": "close",
		"ignore-list": [
			"Alacritty"
		],
		"app_ids-mapping": {
			"firefoxdeveloperedition": "firefox-developer-edition"
		}
	},

    "custom/spotify": {
        "exec": "mediaplayer.py --player spotify",
        "format": " {}",
        "rotate": 0,
        "return-type": "json",
        "on-click": "playerctl play-pause --player spotify",
        "on-click-right": "playerctl next --player spotify",
        "on-click-middle": "playerctl previous --player spotify",
        "on-scroll-up": "volumecontrol.sh -p spotify i",
        "on-scroll-down": "volumecontrol.sh -p spotify d",
        "max-length": 25,
        "escape": true,
        "tooltip": true
    },

    "idle_inhibitor": {
        "format": "{icon}",
        "rotate": 0,
        "format-icons": {
            "activated": "󰥔",
            "deactivated": ""
        }
    },

    "clock": {
        "format": "{:%I:%M %p}",
        "rotate": 0,
        "format-alt": "{:%R 󰃭 %d·%m·%y}",
        "tooltip-format": "<span>{calendar}</span>",
        "calendar": {
            "mode": "month",
            "mode-mon-col": 3,
            "on-scroll": 1,
            "on-click-right": "mode",
            "format": {
                "months": "<span color='#ffead3'><b>{}</b></span>",
                "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
                "today": "<span color='#ff6699'><b>{}</b></span>"
            }
        },
        "actions": {
            "on-click-right": "mode",
            "on-click-forward": "tz_up",
            "on-click-backward": "tz_down",
            "on-scroll-up": "shift_up",
            "on-scroll-down": "shift_down"
        }
    },

    "tray": {
        "icon-size": 18,
        "rotate": 0,
        "spacing": 5
    },

    "battery": {
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "rotate": 0,
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },

    "backlight": {
        "device": "intel_backlight",
        "rotate": 0,
        "format": "{icon} {percent}%",
        "format-icons": ["", "", "", "", "", "", "", "", ""],
        "on-scroll-up": "brightnessctl set 1%+",
        "on-scroll-down": "brightnessctl set 1%-",
        "min-length": 6
    },

    "network": {
        "tooltip": true,
        "format-wifi": "",
        "rotate": 0,
        "format-ethernet": "󰈀 ",
        "tooltip-format": "Network: <big><b>{essid}</b></big>\nSignal strength: <b>{signaldBm}dBm ({signalStrength}%)</b>\nFrequency: <b>{frequency}MHz</b>\nInterface: <b>{ifname}</b>\nIP: <b>{ipaddr}/{cidr}</b>\nGateway: <b>{gwaddr}</b>\nNetmask: <b>{netmask}</b>",
        "format-linked": "󰈀 {ifname} (No IP)",
        "format-disconnected": "󰖪 ",
        "tooltip-format-disconnected": "Disconnected",
        "format-alt": "<span foreground='#99ffdd'> {bandwidthDownBytes}</span> <span foreground='#ffcc66'> {bandwidthUpBytes}</span>",
        "interval": 2,
    },

    "pulseaudio": {
        "format": "{icon} {volume}%",
        "rotate": 0,
        "format-muted": "婢",
        "on-click": "pavucontrol -t 3",
        "on-click-middle": "volumecontrol.sh -o m",
        "on-scroll-up": "volumecontrol.sh -o i",
        "on-scroll-down": "volumecontrol.sh -o d",
        "tooltip-format": "{icon} {desc} // {volume}%",
        "scroll-step": 5,
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        }
    },

    "pulseaudio#microphone": {
        "format": "{format_source}",
        "rotate": 0,
        "format-source": "",
        "format-source-muted": "",
        "on-click": "pavucontrol -t 4",
        "on-click-middle": "volumecontrol.sh -i m",
        "on-scroll-up": "volumecontrol.sh -i i",
        "on-scroll-down": "volumecontrol.sh -i d",
        "tooltip-format": "{format_source} {source_desc} // {source_volume}%",
        "scroll-step": 5
    },

    "custom/notifications": {
        "tooltip": false,
        "format": "{icon} {}",
        "rotate": 0,
        "format-icons": {
            "email-notification": "<span foreground='white'><sup></sup></span>",
            "chat-notification": "󱋊<span foreground='white'><sup></sup></span>",
            "warning-notification": "󱨪<span foreground='yellow'><sup></sup></span>",
            "error-notification": "󱨪<span foreground='red'><sup></sup></span>",
            "network-notification": "󱂇<span foreground='white'><sup></sup></span>",
            "battery-notification": "󰁺<span foreground='white'><sup></sup></span>",
            "update-notification": "󰚰<span foreground='white'><sup></sup></span>",
            "music-notification": "󰝚<span foreground='white'><sup></sup></span>",
            "volume-notification": "󰕿<span foreground='white'><sup></sup></span>",
            "notification": "<span foreground='white'><sup></sup></span>",
            "none": ""
        },
        "return-type": "json",
        "exec-if": "which dunstctl",
        "exec": "notifications.py",
        "on-click": "sleep 0.1 && dunstctl history-pop",
        "on-click-middle": "dunstctl history-clear",
        "on-click-right": "dunstctl close-all",
        "interval": 1,
        "tooltip": true,
        "escape": true
    },

    "custom/keybindhint": {
        "format": " ",
        "rotate": 0,
        "on-click": "keybinds_hint.sh"
    },

    "hyprland/workspaces#kanji": {
	"disable-scroll": true,
	"show-special": false,
	"all-outputs": true,
	"format": "{icon}",
    "persistent-workspaces": {
      "*": 3

	},
	"format-icons": {
		"1": "一",
		"2": "二",
		"3": "三",
		"4": "四",
		"5": "五",
		"6": "六",
		"7": "七",
		"8": "八",
		"9": "九",
		"10": "十",
	}
},



// modules for padding //

    "custom/l_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/r_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/sl_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/sr_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/rl_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/rr_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/padd": {
        "format": "  ",
        "interval" : "once",
        "tooltip": false
    }

}
